# Copyright (C) 2019, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Wazuh StorageClass

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wazuh-storage
provisioner: nfs.csi.k8s.io # Updated to use NFS CSI driver
parameters:
  server: <NFS_SERVER_ADDRESS> # Replace with your NFS server address
  share: <NFS_SHARE_PATH>      # Replace with your NFS share path
  readOnly: "false"           # Optional: Set to "true" if the share is read-only